#!/bin/env sh

[ $(id -u) -eq 0 ] && echo 'This script should not be ran as root' && exit 1

PROF_DIR=profile.default-release

echo 'Generating custom firefox config'
wget https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js $PROF_DIR/
cat custom-user.js >> $PROF_DIR/user.js

echo 'Installing config to firefox'
dir_count=0
for i in ~/.mozilla/firefox/*.default-release/; do
	((++dir_count))
	cp -fr $PROF_DIR/* $i
done

[ $dir_count -eq 0 ] && echo 'No FireFox directories were found. Was FireFox ran atleast once after install?' && exit 1

echo 'FireFox successfully configured, however, theme and search engine must be set manually. See README for more info.'
